[project]
name = "battle-score-aggregator"
version = "1.1"
description = "A Battle of the Books scoring system for the Northville District Library."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bcrypt==4.3.0",
    "coloredlogs>=15.0.1",
    "jinja2>=3.1.6",
    "marshmallow>=4.2.2",
    "passlib>=1.7.4",
    "sanic>=25.12.0",
    "sanic-jinja2>=2022.11.11",
    "sanic-sessions>=0.9.0",
    "toml>=0.10.2",
]
